// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCredentialService is an autogenerated mock type for the CredentialService type
type MockCredentialService struct {
	mock.Mock
}

type MockCredentialService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialService) EXPECT() *MockCredentialService_Expecter {
	return &MockCredentialService_Expecter{mock: &_m.Mock}
}

// GetConnectURL provides a mock function with given fields: ctx, externalUserID
func (_m *MockCredentialService) GetConnectURL(ctx context.Context, externalUserID string) (string, error) {
	ret := _m.Called(ctx, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, externalUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, externalUserID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCredentialService_GetConnectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectURL'
type MockCredentialService_GetConnectURL_Call struct {
	*mock.Call
}

// GetConnectURL is a helper method to define mock.On call
//   - ctx context.Context
//   - externalUserID string
func (_e *MockCredentialService_Expecter) GetConnectURL(ctx interface{}, externalUserID interface{}) *MockCredentialService_GetConnectURL_Call {
	return &MockCredentialService_GetConnectURL_Call{Call: _e.mock.On("GetConnectURL", ctx, externalUserID)}
}

func (_c *MockCredentialService_GetConnectURL_Call) Run(run func(ctx context.Context, externalUserID string)) *MockCredentialService_GetConnectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCredentialService_GetConnectURL_Call) Return(_a0 string, _a1 error) *MockCredentialService_GetConnectURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCredentialService_GetConnectURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockCredentialService_GetConnectURL_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCredential provides a mock function with given fields: ctx, credentialID, externalUserID
func (_m *MockCredentialService) SaveCredential(ctx context.Context, credentialID string, externalUserID string) error {
	ret := _m.Called(ctx, credentialID, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credentialID, externalUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialService_SaveCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCredential'
type MockCredentialService_SaveCredential_Call struct {
	*mock.Call
}

// SaveCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
//   - externalUserID string
func (_e *MockCredentialService_Expecter) SaveCredential(ctx interface{}, credentialID interface{}, externalUserID interface{}) *MockCredentialService_SaveCredential_Call {
	return &MockCredentialService_SaveCredential_Call{Call: _e.mock.On("SaveCredential", ctx, credentialID, externalUserID)}
}

func (_c *MockCredentialService_SaveCredential_Call) Run(run func(ctx context.Context, credentialID string, externalUserID string)) *MockCredentialService_SaveCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialService_SaveCredential_Call) Return(_a0 error) *MockCredentialService_SaveCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialService_SaveCredential_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCredentialService_SaveCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialService creates a new instance of MockCredentialService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialService {
	mock := &MockCredentialService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
