// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/stefanobassani-dev/money-tracker/internal/models"
)

// MockTinkClient is an autogenerated mock type for the TinkClient type
type MockTinkClient struct {
	mock.Mock
}

type MockTinkClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTinkClient) EXPECT() *MockTinkClient_Expecter {
	return &MockTinkClient_Expecter{mock: &_m.Mock}
}

// BuildUrl provides a mock function with given fields: code, state
func (_m *MockTinkClient) BuildUrl(code string, state string) string {
	ret := _m.Called(code, state)

	if len(ret) == 0 {
		panic("no return value specified for BuildUrl")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(code, state)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTinkClient_BuildUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildUrl'
type MockTinkClient_BuildUrl_Call struct {
	*mock.Call
}

// BuildUrl is a helper method to define mock.On call
//   - code string
//   - state string
func (_e *MockTinkClient_Expecter) BuildUrl(code interface{}, state interface{}) *MockTinkClient_BuildUrl_Call {
	return &MockTinkClient_BuildUrl_Call{Call: _e.mock.On("BuildUrl", code, state)}
}

func (_c *MockTinkClient_BuildUrl_Call) Run(run func(code string, state string)) *MockTinkClient_BuildUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockTinkClient_BuildUrl_Call) Return(_a0 string) *MockTinkClient_BuildUrl_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTinkClient_BuildUrl_Call) RunAndReturn(run func(string, string) string) *MockTinkClient_BuildUrl_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, externalID
func (_m *MockTinkClient) CreateUser(ctx context.Context, externalID string) (string, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockTinkClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockTinkClient_Expecter) CreateUser(ctx interface{}, externalID interface{}) *MockTinkClient_CreateUser_Call {
	return &MockTinkClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, externalID)}
}

func (_c *MockTinkClient_CreateUser_Call) Run(run func(ctx context.Context, externalID string)) *MockTinkClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTinkClient_CreateUser_Call) Return(_a0 string, _a1 error) *MockTinkClient_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_CreateUser_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTinkClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExchangeUserToken provides a mock function with given fields: ctx, externalID, scopes
func (_m *MockTinkClient) ExchangeUserToken(ctx context.Context, externalID string, scopes []string) (string, error) {
	ret := _m.Called(ctx, externalID, scopes)

	if len(ret) == 0 {
		panic("no return value specified for ExchangeUserToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, error)); ok {
		return rf(ctx, externalID, scopes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, externalID, scopes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, externalID, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_ExchangeUserToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExchangeUserToken'
type MockTinkClient_ExchangeUserToken_Call struct {
	*mock.Call
}

// ExchangeUserToken is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - scopes []string
func (_e *MockTinkClient_Expecter) ExchangeUserToken(ctx interface{}, externalID interface{}, scopes interface{}) *MockTinkClient_ExchangeUserToken_Call {
	return &MockTinkClient_ExchangeUserToken_Call{Call: _e.mock.On("ExchangeUserToken", ctx, externalID, scopes)}
}

func (_c *MockTinkClient_ExchangeUserToken_Call) Run(run func(ctx context.Context, externalID string, scopes []string)) *MockTinkClient_ExchangeUserToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTinkClient_ExchangeUserToken_Call) Return(_a0 string, _a1 error) *MockTinkClient_ExchangeUserToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_ExchangeUserToken_Call) RunAndReturn(run func(context.Context, string, []string) (string, error)) *MockTinkClient_ExchangeUserToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationGrant provides a mock function with given fields: ctx, externalID, scopes
func (_m *MockTinkClient) GetAuthorizationGrant(ctx context.Context, externalID string, scopes []string) (string, error) {
	ret := _m.Called(ctx, externalID, scopes)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationGrant")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, error)); ok {
		return rf(ctx, externalID, scopes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, externalID, scopes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, externalID, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_GetAuthorizationGrant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationGrant'
type MockTinkClient_GetAuthorizationGrant_Call struct {
	*mock.Call
}

// GetAuthorizationGrant is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - scopes []string
func (_e *MockTinkClient_Expecter) GetAuthorizationGrant(ctx interface{}, externalID interface{}, scopes interface{}) *MockTinkClient_GetAuthorizationGrant_Call {
	return &MockTinkClient_GetAuthorizationGrant_Call{Call: _e.mock.On("GetAuthorizationGrant", ctx, externalID, scopes)}
}

func (_c *MockTinkClient_GetAuthorizationGrant_Call) Run(run func(ctx context.Context, externalID string, scopes []string)) *MockTinkClient_GetAuthorizationGrant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTinkClient_GetAuthorizationGrant_Call) Return(_a0 string, _a1 error) *MockTinkClient_GetAuthorizationGrant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_GetAuthorizationGrant_Call) RunAndReturn(run func(context.Context, string, []string) (string, error)) *MockTinkClient_GetAuthorizationGrant_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorizationGrantDelegate provides a mock function with given fields: ctx, externalID, scopes
func (_m *MockTinkClient) GetAuthorizationGrantDelegate(ctx context.Context, externalID string, scopes []string) (string, error) {
	ret := _m.Called(ctx, externalID, scopes)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorizationGrantDelegate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) (string, error)); ok {
		return rf(ctx, externalID, scopes)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) string); ok {
		r0 = rf(ctx, externalID, scopes)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []string) error); ok {
		r1 = rf(ctx, externalID, scopes)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_GetAuthorizationGrantDelegate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorizationGrantDelegate'
type MockTinkClient_GetAuthorizationGrantDelegate_Call struct {
	*mock.Call
}

// GetAuthorizationGrantDelegate is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - scopes []string
func (_e *MockTinkClient_Expecter) GetAuthorizationGrantDelegate(ctx interface{}, externalID interface{}, scopes interface{}) *MockTinkClient_GetAuthorizationGrantDelegate_Call {
	return &MockTinkClient_GetAuthorizationGrantDelegate_Call{Call: _e.mock.On("GetAuthorizationGrantDelegate", ctx, externalID, scopes)}
}

func (_c *MockTinkClient_GetAuthorizationGrantDelegate_Call) Run(run func(ctx context.Context, externalID string, scopes []string)) *MockTinkClient_GetAuthorizationGrantDelegate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockTinkClient_GetAuthorizationGrantDelegate_Call) Return(_a0 string, _a1 error) *MockTinkClient_GetAuthorizationGrantDelegate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_GetAuthorizationGrantDelegate_Call) RunAndReturn(run func(context.Context, string, []string) (string, error)) *MockTinkClient_GetAuthorizationGrantDelegate_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByExternalID provides a mock function with given fields: ctx, externalID
func (_m *MockTinkClient) GetUserByExternalID(ctx context.Context, externalID string) (string, error) {
	ret := _m.Called(ctx, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByExternalID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, externalID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_GetUserByExternalID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByExternalID'
type MockTinkClient_GetUserByExternalID_Call struct {
	*mock.Call
}

// GetUserByExternalID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
func (_e *MockTinkClient_Expecter) GetUserByExternalID(ctx interface{}, externalID interface{}) *MockTinkClient_GetUserByExternalID_Call {
	return &MockTinkClient_GetUserByExternalID_Call{Call: _e.mock.On("GetUserByExternalID", ctx, externalID)}
}

func (_c *MockTinkClient_GetUserByExternalID_Call) Run(run func(ctx context.Context, externalID string)) *MockTinkClient_GetUserByExternalID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTinkClient_GetUserByExternalID_Call) Return(_a0 string, _a1 error) *MockTinkClient_GetUserByExternalID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_GetUserByExternalID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTinkClient_GetUserByExternalID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCredential provides a mock function with given fields: ctx, credentialID, externalID
func (_m *MockTinkClient) GetUserCredential(ctx context.Context, credentialID string, externalID string) (*models.Credential, error) {
	ret := _m.Called(ctx, credentialID, externalID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCredential")
	}

	var r0 *models.Credential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Credential, error)); ok {
		return rf(ctx, credentialID, externalID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Credential); ok {
		r0 = rf(ctx, credentialID, externalID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Credential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, credentialID, externalID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_GetUserCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCredential'
type MockTinkClient_GetUserCredential_Call struct {
	*mock.Call
}

// GetUserCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
//   - externalID string
func (_e *MockTinkClient_Expecter) GetUserCredential(ctx interface{}, credentialID interface{}, externalID interface{}) *MockTinkClient_GetUserCredential_Call {
	return &MockTinkClient_GetUserCredential_Call{Call: _e.mock.On("GetUserCredential", ctx, credentialID, externalID)}
}

func (_c *MockTinkClient_GetUserCredential_Call) Run(run func(ctx context.Context, credentialID string, externalID string)) *MockTinkClient_GetUserCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTinkClient_GetUserCredential_Call) Return(_a0 *models.Credential, _a1 error) *MockTinkClient_GetUserCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_GetUserCredential_Call) RunAndReturn(run func(context.Context, string, string) (*models.Credential, error)) *MockTinkClient_GetUserCredential_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserToken provides a mock function with given fields: ctx, code
func (_m *MockTinkClient) GetUserToken(ctx context.Context, code string) (string, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetUserToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, code)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkClient_GetUserToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserToken'
type MockTinkClient_GetUserToken_Call struct {
	*mock.Call
}

// GetUserToken is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockTinkClient_Expecter) GetUserToken(ctx interface{}, code interface{}) *MockTinkClient_GetUserToken_Call {
	return &MockTinkClient_GetUserToken_Call{Call: _e.mock.On("GetUserToken", ctx, code)}
}

func (_c *MockTinkClient_GetUserToken_Call) Run(run func(ctx context.Context, code string)) *MockTinkClient_GetUserToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTinkClient_GetUserToken_Call) Return(_a0 string, _a1 error) *MockTinkClient_GetUserToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkClient_GetUserToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTinkClient_GetUserToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTinkClient creates a new instance of MockTinkClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTinkClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTinkClient {
	mock := &MockTinkClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
