// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/stefanobassani-dev/money-tracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockCredentialRepository is an autogenerated mock type for the CredentialRepository type
type MockCredentialRepository struct {
	mock.Mock
}

type MockCredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCredentialRepository) EXPECT() *MockCredentialRepository_Expecter {
	return &MockCredentialRepository_Expecter{mock: &_m.Mock}
}

// CreateCredential provides a mock function with given fields: ctx, credential
func (_m *MockCredentialRepository) CreateCredential(ctx context.Context, credential domain.Credential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Credential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialRepository_CreateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredential'
type MockCredentialRepository_CreateCredential_Call struct {
	*mock.Call
}

// CreateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credential domain.Credential
func (_e *MockCredentialRepository_Expecter) CreateCredential(ctx interface{}, credential interface{}) *MockCredentialRepository_CreateCredential_Call {
	return &MockCredentialRepository_CreateCredential_Call{Call: _e.mock.On("CreateCredential", ctx, credential)}
}

func (_c *MockCredentialRepository_CreateCredential_Call) Run(run func(ctx context.Context, credential domain.Credential)) *MockCredentialRepository_CreateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Credential))
	})
	return _c
}

func (_c *MockCredentialRepository_CreateCredential_Call) Return(_a0 error) *MockCredentialRepository_CreateCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialRepository_CreateCredential_Call) RunAndReturn(run func(context.Context, domain.Credential) error) *MockCredentialRepository_CreateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// CreatePendingCredential provides a mock function with given fields: ctx, credentialID, userID
func (_m *MockCredentialRepository) CreatePendingCredential(ctx context.Context, credentialID string, userID string) error {
	ret := _m.Called(ctx, credentialID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreatePendingCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credentialID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCredentialRepository_CreatePendingCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePendingCredential'
type MockCredentialRepository_CreatePendingCredential_Call struct {
	*mock.Call
}

// CreatePendingCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
//   - userID string
func (_e *MockCredentialRepository_Expecter) CreatePendingCredential(ctx interface{}, credentialID interface{}, userID interface{}) *MockCredentialRepository_CreatePendingCredential_Call {
	return &MockCredentialRepository_CreatePendingCredential_Call{Call: _e.mock.On("CreatePendingCredential", ctx, credentialID, userID)}
}

func (_c *MockCredentialRepository_CreatePendingCredential_Call) Run(run func(ctx context.Context, credentialID string, userID string)) *MockCredentialRepository_CreatePendingCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockCredentialRepository_CreatePendingCredential_Call) Return(_a0 error) *MockCredentialRepository_CreatePendingCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCredentialRepository_CreatePendingCredential_Call) RunAndReturn(run func(context.Context, string, string) error) *MockCredentialRepository_CreatePendingCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCredentialRepository creates a new instance of MockCredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCredentialRepository {
	mock := &MockCredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
