// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTinkService is an autogenerated mock type for the TinkService type
type MockTinkService struct {
	mock.Mock
}

type MockTinkService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTinkService) EXPECT() *MockTinkService_Expecter {
	return &MockTinkService_Expecter{mock: &_m.Mock}
}

// GetConnectURL provides a mock function with given fields: ctx, externalUserID
func (_m *MockTinkService) GetConnectURL(ctx context.Context, externalUserID string) (string, error) {
	ret := _m.Called(ctx, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, externalUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, externalUserID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, externalUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkService_GetConnectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectURL'
type MockTinkService_GetConnectURL_Call struct {
	*mock.Call
}

// GetConnectURL is a helper method to define mock.On call
//   - ctx context.Context
//   - externalUserID string
func (_e *MockTinkService_Expecter) GetConnectURL(ctx interface{}, externalUserID interface{}) *MockTinkService_GetConnectURL_Call {
	return &MockTinkService_GetConnectURL_Call{Call: _e.mock.On("GetConnectURL", ctx, externalUserID)}
}

func (_c *MockTinkService_GetConnectURL_Call) Run(run func(ctx context.Context, externalUserID string)) *MockTinkService_GetConnectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTinkService_GetConnectURL_Call) Return(_a0 string, _a1 error) *MockTinkService_GetConnectURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkService_GetConnectURL_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTinkService_GetConnectURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrCreateTinkUser provides a mock function with given fields: ctx, userID
func (_m *MockTinkService) GetOrCreateTinkUser(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateTinkUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTinkService_GetOrCreateTinkUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateTinkUser'
type MockTinkService_GetOrCreateTinkUser_Call struct {
	*mock.Call
}

// GetOrCreateTinkUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTinkService_Expecter) GetOrCreateTinkUser(ctx interface{}, userID interface{}) *MockTinkService_GetOrCreateTinkUser_Call {
	return &MockTinkService_GetOrCreateTinkUser_Call{Call: _e.mock.On("GetOrCreateTinkUser", ctx, userID)}
}

func (_c *MockTinkService_GetOrCreateTinkUser_Call) Run(run func(ctx context.Context, userID string)) *MockTinkService_GetOrCreateTinkUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTinkService_GetOrCreateTinkUser_Call) Return(_a0 string, _a1 error) *MockTinkService_GetOrCreateTinkUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTinkService_GetOrCreateTinkUser_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockTinkService_GetOrCreateTinkUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveCredential provides a mock function with given fields: ctx, credentialID, externalUserID
func (_m *MockTinkService) SaveCredential(ctx context.Context, credentialID string, externalUserID string) error {
	ret := _m.Called(ctx, credentialID, externalUserID)

	if len(ret) == 0 {
		panic("no return value specified for SaveCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credentialID, externalUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTinkService_SaveCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveCredential'
type MockTinkService_SaveCredential_Call struct {
	*mock.Call
}

// SaveCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
//   - externalUserID string
func (_e *MockTinkService_Expecter) SaveCredential(ctx interface{}, credentialID interface{}, externalUserID interface{}) *MockTinkService_SaveCredential_Call {
	return &MockTinkService_SaveCredential_Call{Call: _e.mock.On("SaveCredential", ctx, credentialID, externalUserID)}
}

func (_c *MockTinkService_SaveCredential_Call) Run(run func(ctx context.Context, credentialID string, externalUserID string)) *MockTinkService_SaveCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockTinkService_SaveCredential_Call) Return(_a0 error) *MockTinkService_SaveCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTinkService_SaveCredential_Call) RunAndReturn(run func(context.Context, string, string) error) *MockTinkService_SaveCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTinkService creates a new instance of MockTinkService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTinkService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTinkService {
	mock := &MockTinkService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
