// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockJWTService is an autogenerated mock type for the JWTService type
type MockJWTService struct {
	mock.Mock
}

type MockJWTService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJWTService) EXPECT() *MockJWTService_Expecter {
	return &MockJWTService_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function with given fields: userID
func (_m *MockJWTService) Generate(userID string) (string, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type MockJWTService_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - userID string
func (_e *MockJWTService_Expecter) Generate(userID interface{}) *MockJWTService_Generate_Call {
	return &MockJWTService_Generate_Call{Call: _e.mock.On("Generate", userID)}
}

func (_c *MockJWTService_Generate_Call) Run(run func(userID string)) *MockJWTService_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_Generate_Call) Return(_a0 string, _a1 error) *MockJWTService_Generate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_Generate_Call) RunAndReturn(run func(string) (string, error)) *MockJWTService_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function with given fields: tokenString
func (_m *MockJWTService) Validate(tokenString string) (string, error) {
	ret := _m.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(tokenString)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(tokenString)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenString)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockJWTService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockJWTService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - tokenString string
func (_e *MockJWTService_Expecter) Validate(tokenString interface{}) *MockJWTService_Validate_Call {
	return &MockJWTService_Validate_Call{Call: _e.mock.On("Validate", tokenString)}
}

func (_c *MockJWTService_Validate_Call) Run(run func(tokenString string)) *MockJWTService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockJWTService_Validate_Call) Return(_a0 string, _a1 error) *MockJWTService_Validate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockJWTService_Validate_Call) RunAndReturn(run func(string) (string, error)) *MockJWTService_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockJWTService creates a new instance of MockJWTService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJWTService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJWTService {
	mock := &MockJWTService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
