// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/stefanobassani-dev/money-tracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// CreateCredential provides a mock function with given fields: ctx, a, credentialID
func (_m *MockAccountRepository) CreateCredential(ctx context.Context, a domain.Account, credentialID string) error {
	ret := _m.Called(ctx, a, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for CreateCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Account, string) error); ok {
		r0 = rf(ctx, a, credentialID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountRepository_CreateCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCredential'
type MockAccountRepository_CreateCredential_Call struct {
	*mock.Call
}

// CreateCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - a domain.Account
//   - credentialID string
func (_e *MockAccountRepository_Expecter) CreateCredential(ctx interface{}, a interface{}, credentialID interface{}) *MockAccountRepository_CreateCredential_Call {
	return &MockAccountRepository_CreateCredential_Call{Call: _e.mock.On("CreateCredential", ctx, a, credentialID)}
}

func (_c *MockAccountRepository_CreateCredential_Call) Run(run func(ctx context.Context, a domain.Account, credentialID string)) *MockAccountRepository_CreateCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Account), args[2].(string))
	})
	return _c
}

func (_c *MockAccountRepository_CreateCredential_Call) Return(_a0 error) *MockAccountRepository_CreateCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountRepository_CreateCredential_Call) RunAndReturn(run func(context.Context, domain.Account, string) error) *MockAccountRepository_CreateCredential_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
