// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/stefanobassani-dev/money-tracker/internal/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// DequeueCredential provides a mock function with given fields: ctx, timeout
func (_m *MockQueue) DequeueCredential(ctx context.Context, timeout time.Duration) (domain.CredentialJobPayload, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for DequeueCredential")
	}

	var r0 domain.CredentialJobPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (domain.CredentialJobPayload, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) domain.CredentialJobPayload); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Get(0).(domain.CredentialJobPayload)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_DequeueCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueCredential'
type MockQueue_DequeueCredential_Call struct {
	*mock.Call
}

// DequeueCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockQueue_Expecter) DequeueCredential(ctx interface{}, timeout interface{}) *MockQueue_DequeueCredential_Call {
	return &MockQueue_DequeueCredential_Call{Call: _e.mock.On("DequeueCredential", ctx, timeout)}
}

func (_c *MockQueue_DequeueCredential_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockQueue_DequeueCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockQueue_DequeueCredential_Call) Return(_a0 domain.CredentialJobPayload, _a1 error) *MockQueue_DequeueCredential_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_DequeueCredential_Call) RunAndReturn(run func(context.Context, time.Duration) (domain.CredentialJobPayload, error)) *MockQueue_DequeueCredential_Call {
	_c.Call.Return(run)
	return _c
}

// DequeueSync provides a mock function with given fields: ctx, timeout
func (_m *MockQueue) DequeueSync(ctx context.Context, timeout time.Duration) (domain.SyncJobPayload, error) {
	ret := _m.Called(ctx, timeout)

	if len(ret) == 0 {
		panic("no return value specified for DequeueSync")
	}

	var r0 domain.SyncJobPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) (domain.SyncJobPayload, error)); ok {
		return rf(ctx, timeout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Duration) domain.SyncJobPayload); ok {
		r0 = rf(ctx, timeout)
	} else {
		r0 = ret.Get(0).(domain.SyncJobPayload)
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = rf(ctx, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueue_DequeueSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueSync'
type MockQueue_DequeueSync_Call struct {
	*mock.Call
}

// DequeueSync is a helper method to define mock.On call
//   - ctx context.Context
//   - timeout time.Duration
func (_e *MockQueue_Expecter) DequeueSync(ctx interface{}, timeout interface{}) *MockQueue_DequeueSync_Call {
	return &MockQueue_DequeueSync_Call{Call: _e.mock.On("DequeueSync", ctx, timeout)}
}

func (_c *MockQueue_DequeueSync_Call) Run(run func(ctx context.Context, timeout time.Duration)) *MockQueue_DequeueSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockQueue_DequeueSync_Call) Return(_a0 domain.SyncJobPayload, _a1 error) *MockQueue_DequeueSync_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueue_DequeueSync_Call) RunAndReturn(run func(context.Context, time.Duration) (domain.SyncJobPayload, error)) *MockQueue_DequeueSync_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueCredential provides a mock function with given fields: ctx, credID, userID
func (_m *MockQueue) EnqueueCredential(ctx context.Context, credID string, userID string) error {
	ret := _m.Called(ctx, credID, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueCredential")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_EnqueueCredential_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueCredential'
type MockQueue_EnqueueCredential_Call struct {
	*mock.Call
}

// EnqueueCredential is a helper method to define mock.On call
//   - ctx context.Context
//   - credID string
//   - userID string
func (_e *MockQueue_Expecter) EnqueueCredential(ctx interface{}, credID interface{}, userID interface{}) *MockQueue_EnqueueCredential_Call {
	return &MockQueue_EnqueueCredential_Call{Call: _e.mock.On("EnqueueCredential", ctx, credID, userID)}
}

func (_c *MockQueue_EnqueueCredential_Call) Run(run func(ctx context.Context, credID string, userID string)) *MockQueue_EnqueueCredential_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockQueue_EnqueueCredential_Call) Return(_a0 error) *MockQueue_EnqueueCredential_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_EnqueueCredential_Call) RunAndReturn(run func(context.Context, string, string) error) *MockQueue_EnqueueCredential_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueSync provides a mock function with given fields: ctx, credID, userID
func (_m *MockQueue) EnqueueSync(ctx context.Context, credID string, userID string) error {
	ret := _m.Called(ctx, credID, userID)

	if len(ret) == 0 {
		panic("no return value specified for EnqueueSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQueue_EnqueueSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueSync'
type MockQueue_EnqueueSync_Call struct {
	*mock.Call
}

// EnqueueSync is a helper method to define mock.On call
//   - ctx context.Context
//   - credID string
//   - userID string
func (_e *MockQueue_Expecter) EnqueueSync(ctx interface{}, credID interface{}, userID interface{}) *MockQueue_EnqueueSync_Call {
	return &MockQueue_EnqueueSync_Call{Call: _e.mock.On("EnqueueSync", ctx, credID, userID)}
}

func (_c *MockQueue_EnqueueSync_Call) Run(run func(ctx context.Context, credID string, userID string)) *MockQueue_EnqueueSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockQueue_EnqueueSync_Call) Return(_a0 error) *MockQueue_EnqueueSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQueue_EnqueueSync_Call) RunAndReturn(run func(context.Context, string, string) error) *MockQueue_EnqueueSync_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
