// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTransactionService is an autogenerated mock type for the TransactionService type
type MockTransactionService struct {
	mock.Mock
}

type MockTransactionService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionService) EXPECT() *MockTransactionService_Expecter {
	return &MockTransactionService_Expecter{mock: &_m.Mock}
}

// SaveTransactions provides a mock function with given fields: ctx, userID
func (_m *MockTransactionService) SaveTransactions(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveTransactions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionService_SaveTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTransactions'
type MockTransactionService_SaveTransactions_Call struct {
	*mock.Call
}

// SaveTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockTransactionService_Expecter) SaveTransactions(ctx interface{}, userID interface{}) *MockTransactionService_SaveTransactions_Call {
	return &MockTransactionService_SaveTransactions_Call{Call: _e.mock.On("SaveTransactions", ctx, userID)}
}

func (_c *MockTransactionService_SaveTransactions_Call) Run(run func(ctx context.Context, userID string)) *MockTransactionService_SaveTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransactionService_SaveTransactions_Call) Return(_a0 error) *MockTransactionService_SaveTransactions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionService_SaveTransactions_Call) RunAndReturn(run func(context.Context, string) error) *MockTransactionService_SaveTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionService creates a new instance of MockTransactionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionService {
	mock := &MockTransactionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
