// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// GetOrCreateTinkUser provides a mock function with given fields: ctx, userID
func (_m *MockUserService) GetOrCreateTinkUser(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreateTinkUser")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserService_GetOrCreateTinkUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrCreateTinkUser'
type MockUserService_GetOrCreateTinkUser_Call struct {
	*mock.Call
}

// GetOrCreateTinkUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserService_Expecter) GetOrCreateTinkUser(ctx interface{}, userID interface{}) *MockUserService_GetOrCreateTinkUser_Call {
	return &MockUserService_GetOrCreateTinkUser_Call{Call: _e.mock.On("GetOrCreateTinkUser", ctx, userID)}
}

func (_c *MockUserService_GetOrCreateTinkUser_Call) Run(run func(ctx context.Context, userID string)) *MockUserService_GetOrCreateTinkUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserService_GetOrCreateTinkUser_Call) Return(_a0 string, _a1 error) *MockUserService_GetOrCreateTinkUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserService_GetOrCreateTinkUser_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUserService_GetOrCreateTinkUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
