// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/stefanobassani-dev/money-tracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: ctx, email, password
func (_m *MockUserRepository) CreateUser(ctx context.Context, email string, password string) error {
	ret := _m.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockUserRepository_Expecter) CreateUser(ctx interface{}, email interface{}, password interface{}) *MockUserRepository_CreateUser_Call {
	return &MockUserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, password)}
}

func (_c *MockUserRepository_CreateUser_Call) Run(run func(ctx context.Context, email string, password string)) *MockUserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) Return(_a0 error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *MockUserRepository) FindByEmail(ctx context.Context, email string) (*domain.User, string, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *domain.User
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, string, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, email)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockUserRepository_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepository_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) FindByEmail(ctx interface{}, email interface{}) *MockUserRepository_FindByEmail_Call {
	return &MockUserRepository_FindByEmail_Call{Call: _e.mock.On("FindByEmail", ctx, email)}
}

func (_c *MockUserRepository_FindByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) Return(_a0 *domain.User, _a1 string, _a2 error) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockUserRepository_FindByEmail_Call) RunAndReturn(run func(context.Context, string) (*domain.User, string, error)) *MockUserRepository_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetTinkIDByUserID provides a mock function with given fields: ctx, userID
func (_m *MockUserRepository) GetTinkIDByUserID(ctx context.Context, userID string) (string, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTinkIDByUserID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepository_GetTinkIDByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTinkIDByUserID'
type MockUserRepository_GetTinkIDByUserID_Call struct {
	*mock.Call
}

// GetTinkIDByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockUserRepository_Expecter) GetTinkIDByUserID(ctx interface{}, userID interface{}) *MockUserRepository_GetTinkIDByUserID_Call {
	return &MockUserRepository_GetTinkIDByUserID_Call{Call: _e.mock.On("GetTinkIDByUserID", ctx, userID)}
}

func (_c *MockUserRepository_GetTinkIDByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockUserRepository_GetTinkIDByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserRepository_GetTinkIDByUserID_Call) Return(_a0 string, _a1 error) *MockUserRepository_GetTinkIDByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepository_GetTinkIDByUserID_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockUserRepository_GetTinkIDByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTinkID provides a mock function with given fields: ctx, userID, newTinkID
func (_m *MockUserRepository) UpdateTinkID(ctx context.Context, userID string, newTinkID string) error {
	ret := _m.Called(ctx, userID, newTinkID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTinkID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, newTinkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepository_UpdateTinkID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTinkID'
type MockUserRepository_UpdateTinkID_Call struct {
	*mock.Call
}

// UpdateTinkID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - newTinkID string
func (_e *MockUserRepository_Expecter) UpdateTinkID(ctx interface{}, userID interface{}, newTinkID interface{}) *MockUserRepository_UpdateTinkID_Call {
	return &MockUserRepository_UpdateTinkID_Call{Call: _e.mock.On("UpdateTinkID", ctx, userID, newTinkID)}
}

func (_c *MockUserRepository_UpdateTinkID_Call) Run(run func(ctx context.Context, userID string, newTinkID string)) *MockUserRepository_UpdateTinkID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserRepository_UpdateTinkID_Call) Return(_a0 error) *MockUserRepository_UpdateTinkID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepository_UpdateTinkID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockUserRepository_UpdateTinkID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
