// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// SaveAccountsByCredentialID provides a mock function with given fields: ctx, credentialID, userID
func (_m *MockAccountService) SaveAccountsByCredentialID(ctx context.Context, credentialID string, userID string) error {
	ret := _m.Called(ctx, credentialID, userID)

	if len(ret) == 0 {
		panic("no return value specified for SaveAccountsByCredentialID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, credentialID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountService_SaveAccountsByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAccountsByCredentialID'
type MockAccountService_SaveAccountsByCredentialID_Call struct {
	*mock.Call
}

// SaveAccountsByCredentialID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
//   - userID string
func (_e *MockAccountService_Expecter) SaveAccountsByCredentialID(ctx interface{}, credentialID interface{}, userID interface{}) *MockAccountService_SaveAccountsByCredentialID_Call {
	return &MockAccountService_SaveAccountsByCredentialID_Call{Call: _e.mock.On("SaveAccountsByCredentialID", ctx, credentialID, userID)}
}

func (_c *MockAccountService_SaveAccountsByCredentialID_Call) Run(run func(ctx context.Context, credentialID string, userID string)) *MockAccountService_SaveAccountsByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockAccountService_SaveAccountsByCredentialID_Call) Return(_a0 error) *MockAccountService_SaveAccountsByCredentialID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountService_SaveAccountsByCredentialID_Call) RunAndReturn(run func(context.Context, string, string) error) *MockAccountService_SaveAccountsByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
