// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/stefanobassani-dev/money-tracker/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockTransactionRepository is an autogenerated mock type for the TransactionRepository type
type MockTransactionRepository struct {
	mock.Mock
}

type MockTransactionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRepository) EXPECT() *MockTransactionRepository_Expecter {
	return &MockTransactionRepository_Expecter{mock: &_m.Mock}
}

// UpsertBatch provides a mock function with given fields: ctx, txs
func (_m *MockTransactionRepository) UpsertBatch(ctx context.Context, txs []domain.Transaction) error {
	ret := _m.Called(ctx, txs)

	if len(ret) == 0 {
		panic("no return value specified for UpsertBatch")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.Transaction) error); ok {
		r0 = rf(ctx, txs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransactionRepository_UpsertBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertBatch'
type MockTransactionRepository_UpsertBatch_Call struct {
	*mock.Call
}

// UpsertBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - txs []domain.Transaction
func (_e *MockTransactionRepository_Expecter) UpsertBatch(ctx interface{}, txs interface{}) *MockTransactionRepository_UpsertBatch_Call {
	return &MockTransactionRepository_UpsertBatch_Call{Call: _e.mock.On("UpsertBatch", ctx, txs)}
}

func (_c *MockTransactionRepository_UpsertBatch_Call) Run(run func(ctx context.Context, txs []domain.Transaction)) *MockTransactionRepository_UpsertBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.Transaction))
	})
	return _c
}

func (_c *MockTransactionRepository_UpsertBatch_Call) Return(_a0 error) *MockTransactionRepository_UpsertBatch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransactionRepository_UpsertBatch_Call) RunAndReturn(run func(context.Context, []domain.Transaction) error) *MockTransactionRepository_UpsertBatch_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransactionRepository creates a new instance of MockTransactionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRepository {
	mock := &MockTransactionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
